# -*- mode: python ; coding: utf-8 -*-
# Сборка каталога dist/TaskTimer/ для .deb (Linux amd64, onedir — надёжнее для Qt).

a = Analysis(
    ["app.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        "timerapp_ag.main",
        "timerapp_ag.main_window",
        "timerapp_ag.controller",
        "timerapp_ag.storage",
        "timerapp_ag.models",
        "timerapp_ag.bitrix",
        "timerapp_ag.bitrix_config",
        "timerapp_ag.single_instance",
        "timerapp_ag.webdav_config",
        "timerapp_ag.webdav_client",
        "timerapp_ag.webdav_sync",
        "timerapp_ag.webdav_meta",
        "timerapp_ag.secure_files",
        "timerapp_ag.bitrix_secrets",
        "timerapp_ag.shutdown_backup",
        "timerapp_ag.platform_paths",
        "timerapp_ag.legacy_merge",
        "timerapp_ag.legacy_merge_ui",
        "timerapp_ag.domain",
        "timerapp_ag.domain.state",
        "timerapp_ag.domain.merge",
        "timerapp_ag.domain.queries",
        "timerapp_ag.domain.plan",
        "timerapp_ag.domain.task_ops",
        "timerapp_ag.domain.reminders",
        "timerapp_ag.domain.formatting",
        "timerapp_ag.domain.constants",
        "timerapp_ag.domain.sync_normalize",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TaskTimer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="TaskTimer",
)
