"""Общий список hiddenimports для PyInstaller (.spec)."""

HIDDEN_IMPORTS = [
    "timerapp_ag.main",
    "timerapp_ag.main_window",
    "timerapp_ag.controller",
    "timerapp_ag.storage",
    "timerapp_ag.models",
    "timerapp_ag.bitrix",
    "timerapp_ag.bitrix_config",
    "timerapp_ag.single_instance",
    "timerapp_ag.webdav_config",
    "timerapp_ag.webdav_client",
    "timerapp_ag.webdav_sync",
    "timerapp_ag.webdav_meta",
    "timerapp_ag.secure_files",
    "timerapp_ag.bitrix_secrets",
    "timerapp_ag.shutdown_backup",
    "timerapp_ag.platform_paths",
    "timerapp_ag.legacy_merge",
    "timerapp_ag.legacy_merge_ui",
    "timerapp_ag.app_info",
    "timerapp_ag.domain",
    "timerapp_ag.domain.state",
    "timerapp_ag.domain.merge",
    "timerapp_ag.domain.queries",
    "timerapp_ag.domain.plan",
    "timerapp_ag.domain.task_ops",
    "timerapp_ag.domain.reminders",
    "timerapp_ag.domain.formatting",
    "timerapp_ag.domain.constants",
    "timerapp_ag.domain.sync_normalize",
]
