const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {chromium}=require('playwright');
const publicRoot=path.resolve(__dirname,'../public');
const origin='https://tasktimer.test';
const mime={'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
let browser;
test.beforeEach(async()=>{browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--single-process','--no-zygote','--disable-gpu']});});
test.afterEach(async()=>browser?.close());
async function setup(){const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Europe/Moscow',serviceWorkers:'block'});await context.route(`${origin}/**`,async route=>{const url=new URL(route.request().url()),name=url.pathname==='/'?'index.html':url.pathname.slice(1);try{const body=await fs.readFile(path.join(publicRoot,name));await route.fulfill({body,contentType:mime[path.extname(name)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'not found'});}});const page=await context.newPage();await page.goto(origin);await page.getByText('С чего начнём?').waitFor();return {context,page};}
async function create(page,title){await page.getByTestId('new-task').click();await page.getByTestId('task-title').fill(title);await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});}
async function read(page){return page.evaluate(async()=>{const {openRepository}=await import('/repository.mjs');const r=await openRepository();try{return await r.read();}finally{r.close();}});}
test('mobile CRUD, validation retains input, cancel, history, export/import and deletion',async()=>{
 const {context,page}=await setup();try{
 await create(page,'Проект PWA');assert.equal(await page.getByTestId('task-row').count(),1);
 assert.equal((await read(page)).tasks[0].priority,4);
 await page.getByTestId('add-session').click();await page.getByTestId('session-start').fill('2026-09-29T23:30');await page.getByTestId('session-end').fill('2026-09-29T22:30');await page.getByTestId('session-comment').fill('Через полночь');await page.getByTestId('save').click();await page.locator('#editor-error').waitFor({state:'visible'});assert.equal(await page.getByTestId('session-comment').inputValue(),'Через полночь');
 await page.getByTestId('session-end').fill('2026-09-30T00:30');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});assert.equal(await page.getByTestId('session').count(),1);assert.equal((await read(page)).tasks[0].sessions[0].comment,'Через полночь');
 await page.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await page.getByTestId('session-comment').fill('Отмена');await page.locator('#editor-dialog').getByRole('button',{name:'Отмена',exact:true}).click();assert.equal((await read(page)).tasks[0].sessions[0].comment,'Через полночь');
 await page.getByTestId('task-toggle').click();await page.getByTestId('live-clock').waitFor();await page.reload();await page.getByTestId('live-clock').waitFor();await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).click();await page.locator('#active-timer').waitFor({state:'hidden'});
 const data=await read(page);await page.getByRole('button',{name:'Настройки и резервные копии'}).click();const downloading=page.waitForEvent('download');await page.getByTestId('export').click();const download=await downloading;assert.match(download.suggestedFilename(),/^tasktimer-.*\.json$/);
 await page.getByTestId('import').setInputFiles({name:'copy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.getByTestId('confirm').click();await page.locator('#confirm-dialog').waitFor({state:'hidden'});assert.equal((await read(page)).tasks[0].id,data.tasks[0].id);await page.locator('#settings-dialog').getByRole('button',{name:'Закрыть'}).click();
 await page.locator('.task-select').click();await page.locator('.detail-actions').getByRole('button',{name:'Удалить',exact:true}).click();await page.getByTestId('confirm').click();await page.locator('#confirm-dialog').waitFor({state:'hidden'});assert.equal((await read(page)).tasks.length,0);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no horizontal overflow');
 }finally{await context.close();}
});
test('comment edit preserves exact imported timestamps and metadata',async()=>{const {context,page}=await setup();try{await create(page,'Точность');await page.evaluate(async()=>{const {openRepository}=await import('/repository.mjs');const r=await openRepository();const s=await r.read();s.tasks[0].sessions.push({id:'precision',started_at:'2026-09-28T10:00:00.123456+03:00',ended_at:'2026-09-28T11:00:00.987654+03:00',comment:'До',bitrix_record_id:'123'});await r.dispatch({type:'replaceState',values:s});r.close();});await page.getByTestId('session').waitFor();await page.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await page.getByTestId('session-comment').fill('После');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});const session=(await read(page)).tasks[0].sessions[0];assert.equal(session.started_at,'2026-09-28T10:00:00.123456+03:00');assert.equal(session.ended_at,'2026-09-28T11:00:00.987654+03:00');assert.equal(session.bitrix_record_id,'123');assert.equal(session.comment,'После');}finally{await context.close();}});
test('two tabs refresh and focus expiration closes exactly at saved deadline after reload',async()=>{const {context,page}=await setup();try{await create(page,'Фокус');const second=await context.newPage();await second.goto(origin);await second.getByTestId('task-row').waitFor();await page.getByRole('button',{name:'Концентрация',exact:true}).click();await page.getByTestId('focus-minutes').fill('1');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});await second.getByTestId('live-clock').waitFor();const started=await read(page);assert.ok(started.focus);const deadline=started.focus.ends_at;
 await page.clock.install({time:new Date(new Date(deadline).getTime()+1000)});await page.reload();await page.locator('#task-list .task-row').waitFor();assert.equal((await read(page)).focus,null);assert.equal((await read(page)).tasks[0].sessions[0].ended_at,deadline);await second.locator('#active-timer').waitFor({state:'hidden'});assert.equal((await read(second)).tasks[0].status,'paused');
 }finally{await context.close();}});
test('storage quota error retains form and existing data, retry commits once',async()=>{const {context,page}=await setup();try{await create(page,'Сохранённая');await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){IDBObjectStore.prototype.put=original;throw new DOMException('Недостаточно места на устройстве','QuotaExceededError');};});await page.getByTestId('new-task').click();await page.getByTestId('task-title').fill('После ошибки');await page.getByTestId('save').click();await page.locator('#editor-error').waitFor({state:'visible'});assert.equal(await page.getByTestId('task-title').inputValue(),'После ошибки');assert.equal((await read(page)).tasks.length,1);await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});assert.equal((await read(page)).tasks.length,2);}finally{await context.close();}});
test('comment-only save does not overwrite interval edited in another tab',async()=>{const {context,page}=await setup();try{await create(page,'Совместная правка');await page.getByTestId('add-session').click();await page.getByTestId('session-start').fill('2026-09-29T10:00');await page.getByTestId('session-end').fill('2026-09-29T11:00');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});const second=await context.newPage();await second.goto(origin);await second.locator('.task-select').click();await page.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await page.getByTestId('session-comment').fill('Комментарий другой вкладки');await second.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await second.getByTestId('session-start').fill('2026-09-29T09:30');await second.getByTestId('save').click();await second.locator('#editor-dialog').waitFor({state:'hidden'});const updated=(await read(second)).tasks[0].sessions[0].started_at;await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});const result=(await read(page)).tasks[0].sessions[0];assert.equal(result.started_at,updated);assert.equal(result.comment,'Комментарий другой вкладки');}finally{await context.close();}});
test('time-only and title-only edits preserve newer untouched fields from another tab',async()=>{const {context,page}=await setup();try{await create(page,'Исходное название');await page.getByTestId('add-session').click();await page.getByTestId('session-start').fill('2026-09-29T10:00');await page.getByTestId('session-end').fill('2026-09-29T11:00');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});const second=await context.newPage();await second.goto(origin);await second.locator('.task-select').click();await page.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await page.getByTestId('session-start').fill('2026-09-29T09:00');await second.getByTestId('session').getByRole('button',{name:'Изменить',exact:true}).click();await second.getByTestId('session-comment').fill('Новый комментарий');await second.getByTestId('save').click();await second.locator('#editor-dialog').waitFor({state:'hidden'});await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});assert.equal((await read(page)).tasks[0].sessions[0].comment,'Новый комментарий');await page.locator('.detail-actions').getByRole('button',{name:'Изменить',exact:true}).click();await page.getByTestId('task-title').fill('Новое название');await second.locator('.detail-actions').getByRole('button',{name:'Изменить',exact:true}).click();await second.locator('textarea[name=description]').fill('Новое описание');await second.locator('[name=priority]').selectOption('2');await second.getByTestId('save').click();await second.locator('#editor-dialog').waitFor({state:'hidden'});await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});const task=(await read(page)).tasks[0];assert.equal(task.title,'Новое название');assert.equal(task.description,'Новое описание');assert.equal(task.priority,2);}finally{await context.close();}});
