const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{chromium}=require('playwright');
async function setup({first=false,invalid=false,silent=false,missingGuard=false,delayed=false}={}){const browser=await chromium.launch({timeout:15000,headless:true,args:['--no-sandbox','--single-process','--no-zygote','--disable-dev-shm-usage']});const context=await browser.newContext({serviceWorkers:'block'});const close=context.close.bind(context);context.close=async()=>{await close();await browser.close();};await context.addInitScript(({first,invalid,silent,missingGuard,delayed})=>{if(missingGuard){const add=window.addEventListener.bind(window);window.addEventListener=(name,...args)=>{if(name!=='tasktimer:before-update')add(name,...args);};}const sw=new EventTarget();window.fakeServiceWorker=sw;window.infoReplies=[];let worker;window.updateMessages=[];window.makeWaiting=(revision='revision-2',changes=['Изменение ожидающей версии'])=>{worker=new EventTarget();worker.state='installed';worker.postMessage=(data,ports)=>{window.updateMessages.push(data.type);if(data.type==='TASKTIMER_UPDATE_INFO'&&!silent){const reply=()=>ports[0].postMessage({revision,notes:invalid?{changes:'invalid'}:{title:'Выпуск '+revision,changes}});if(delayed)window.infoReplies.push(reply);else reply();}};window.fakeRegistration.waiting=worker;window.fakeRegistration.installing=worker;window.fakeRegistration.dispatchEvent(new Event('updatefound'));worker.dispatchEvent(new Event('statechange'));};window.fakeRegistration=new EventTarget();Object.assign(window.fakeRegistration,{waiting:null,installing:null,active:{},update:async()=>{}});sw.controller=first?null:{};sw.register=async()=>window.fakeRegistration;Object.defineProperty(navigator,'serviceWorker',{value:sw});if(!first)window.makeWaiting();},{first,invalid,silent,missingGuard,delayed});await context.route('https://notice.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1)||'index.html';try{await route.fulfill({body:await fs.readFile(path.resolve(__dirname,'../public',name)),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/javascript'});}catch{await route.fulfill({status:404});}});const page=await context.newPage();await page.goto('https://notice.test');await page.getByText('С чего начнём?').waitFor();return{page,context};}
test('waiting version banner shows own release notes, Later hides only that revision and settings remains available',async()=>{const{page,context}=await setup();try{await page.locator('[data-pwa-notice]').waitFor({timeout:1500});assert.match(await page.locator('[data-pwa-changes]').textContent(),/Изменение ожидающей версии/);if(process.env.TASKTIMER_NOTICE_ARTIFACT_DIR){const dir=process.env.TASKTIMER_NOTICE_ARTIFACT_DIR;await fs.mkdir(dir,{recursive:true});await page.setViewportSize({width:1440,height:950});await page.screenshot({path:path.join(dir,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(dir,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.getByRole('button',{name:'Позже',exact:true}).click();await page.locator('[data-pwa-notice]').waitFor({state:'hidden'});await page.locator('#settings-button').click();assert.equal(await page.locator('#settings-dialog [data-pwa-update]').isVisible(),true);await page.locator('#settings-dialog .close-dialog').click();await page.evaluate(()=>window.makeWaiting('revision-3',['Новый выпуск']));await page.getByText('Новый выпуск',{exact:true}).waitFor();assert.match(await page.locator('[data-pwa-changes]').textContent(),/Новый выпуск/);}finally{await context.close();}});

test('first installation never shows update notice',async()=>{const{page,context}=await setup({first:true});try{assert.equal(await page.locator('[data-pwa-notice]').isVisible(),false);assert.equal(await page.locator('#settings-dialog [data-pwa-update]').isVisible(),false);}finally{await context.close();}});
test('invalid notes and unanswered worker use generic update notice without unsafe HTML',async()=>{for(const options of [{invalid:true},{silent:true}]){const{page,context}=await setup(options);try{await page.locator('[data-pwa-notice]').waitFor();await page.waitForTimeout(options.silent?2700:100);assert.equal(await page.locator('[data-pwa-changes] li').count(),0);assert.equal(await page.locator('[data-pwa-notice] [data-pwa-update]').isEnabled(),true);}finally{await context.close();}}const{page,context}=await setup();try{await page.evaluate(()=>window.makeWaiting('html',['<img src=x onerror=alert(1)>']));await page.getByText('<img src=x onerror=alert(1)>',{exact:true}).waitFor();assert.equal(await page.locator('[data-pwa-changes] img').count(),0);}finally{await context.close();}});
test('cancel, missing save guard and rejected writes never activate waiting worker and errors show on main screen',async()=>{for(const mode of ['cancel','missing','reject']){const{page,context}=await setup({missingGuard:mode==='missing'});try{await page.locator('[data-pwa-notice]').waitFor();if(mode==='reject')await page.evaluate(()=>window.addEventListener('tasktimer:before-update',e=>e.detail.waitUntil(Promise.reject(Error('save failed')))));page.once('dialog',d=>mode==='cancel'?d.dismiss():d.accept());await page.locator('[data-pwa-notice] [data-pwa-update]').click();if(mode!=='cancel')await page.locator('[data-pwa-update-error]').waitFor();assert.equal((await page.evaluate(()=>window.updateMessages)).includes('TASKTIMER_APPLY_UPDATE'),false);}finally{await context.close();}}});
test('accepted update waits for pending save and refuses a replaced waiting candidate',async()=>{for(const replace of [false,true]){const{page,context}=await setup();try{await page.locator('[data-pwa-notice]').waitFor();await page.evaluate(()=>window.addEventListener('tasktimer:before-update',e=>e.detail.waitUntil(new Promise(resolve=>window.resolveFlush=resolve))));page.once('dialog',d=>d.accept());await page.locator('[data-pwa-notice] [data-pwa-update]').click();await page.waitForFunction(()=>!!window.resolveFlush);assert.equal((await page.evaluate(()=>window.updateMessages)).includes('TASKTIMER_APPLY_UPDATE'),false);if(replace)await page.evaluate(()=>window.makeWaiting('replacement',['Не подтверждённая версия']));await page.evaluate(()=>window.resolveFlush());if(replace){await page.getByText('Ожидающая версия изменилась. Проверьте обновление и подтвердите ещё раз.',{exact:true}).first().waitFor();assert.equal((await page.evaluate(()=>window.updateMessages)).includes('TASKTIMER_APPLY_UPDATE'),false);}else await page.waitForFunction(()=>window.updateMessages.includes('TASKTIMER_APPLY_UPDATE'));}finally{await context.close();}}});
test('Later persists per revision in current tab but a different version returns',async()=>{const{page,context}=await setup();try{await page.getByText('Изменение ожидающей версии',{exact:true}).waitFor();await page.getByRole('button',{name:'Позже',exact:true}).click();await page.reload();await page.getByText('С чего начнём?').waitFor();await page.waitForTimeout(150);assert.equal(await page.locator('[data-pwa-notice]').isVisible(),false);await page.evaluate(()=>window.makeWaiting('revision-new',['Новая версия']));await page.getByText('Новая версия',{exact:true}).waitFor();assert.equal(await page.locator('[data-pwa-notice]').isVisible(),true);}finally{await context.close();}});

test('late stale metadata cannot replace new worker notes and Later before response persists revision',async()=>{const{page,context}=await setup({delayed:true});try{await page.locator('[data-pwa-notice]').waitFor();await page.getByRole('button',{name:'Позже',exact:true}).click();await page.evaluate(()=>window.infoReplies[0]());await page.waitForFunction(()=>sessionStorage.getItem('tasktimer-update-later:/')==='revision-2');assert.equal(await page.locator('[data-pwa-notice]').isVisible(),false);await page.evaluate(()=>{window.makeWaiting('stale',['Неверное']);window.makeWaiting('fresh',['Точное']);});await page.waitForFunction(()=>window.infoReplies.length===3);await page.evaluate(()=>window.infoReplies[2]());await page.getByText('Точное',{exact:true}).waitFor();await page.evaluate(()=>window.infoReplies[1]());await page.waitForTimeout(50);assert.equal(await page.locator('[data-pwa-changes]').textContent(),'Точное');}finally{await context.close();}});
test('another controller cannot trigger reload even after this tab accepted a different worker',async()=>{const{page,context}=await setup();try{await page.locator('[data-pwa-notice]').waitFor();page.once('dialog',d=>d.accept());await page.locator('[data-pwa-notice] [data-pwa-update]').click();await page.waitForFunction(()=>window.updateMessages.includes('TASKTIMER_APPLY_UPDATE'));await page.evaluate(()=>{window.notReloaded='kept';window.fakeServiceWorker.controller={};window.fakeRegistration.waiting=null;window.fakeServiceWorker.dispatchEvent(new Event('controllerchange'));});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.notReloaded),'kept');}finally{await context.close();}});

test('accepted matching update reloads without a duplicate close prompt for the confirmed running timer',async()=>{
 const{page,context}=await setup();try{
 await page.getByTestId('new-task').click();await page.getByTestId('task-title').fill('Работа');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});await page.getByTestId('task-toggle').click();await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).waitFor();
 const dialogs=[];page.on('dialog',async dialog=>{dialogs.push(dialog.type());await(dialog.type()==='confirm'?dialog.accept():dialog.dismiss());});
 await page.locator('[data-pwa-notice] [data-pwa-update]').click();await page.waitForFunction(()=>window.updateMessages.includes('TASKTIMER_APPLY_UPDATE'));
 await page.evaluate(()=>{window.beforeReloadMarker=true;window.fakeServiceWorker.controller=window.fakeRegistration.waiting;window.fakeServiceWorker.dispatchEvent(new Event('controllerchange'));});
 await page.waitForTimeout(200);assert.deepEqual(dialogs,['confirm']);await page.waitForFunction(()=>!window.beforeReloadMarker);await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),true);
 }finally{await context.close();}
});

test('new draft after update consent keeps close protection at controllerchange and cancelled reload preserves it',async()=>{
 const{page,context}=await setup();try{
 page.once('dialog',dialog=>dialog.accept());await page.locator('[data-pwa-notice] [data-pwa-update]').click();await page.waitForFunction(()=>window.updateMessages.includes('TASKTIMER_APPLY_UPDATE'));
 await page.getByTestId('new-task').click();await page.getByTestId('task-title').fill('После согласия');
 const warning=page.waitForEvent('dialog',{timeout:3000});await page.evaluate(()=>{window.fakeServiceWorker.controller=window.fakeRegistration.waiting;setTimeout(()=>window.fakeServiceWorker.dispatchEvent(new Event('controllerchange')),0);});const dialog=await warning;assert.equal(dialog.type(),'beforeunload');await dialog.dismiss();
 assert.equal(await page.getByTestId('task-title').inputValue(),'После согласия');assert.equal(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),true);
 }finally{await context.close();}
});

test('cancelled failed and replaced update never remove the running timer close warning',async()=>{
 for(const mode of ['cancel','failed','replaced']){const{page,context}=await setup();try{
 await page.getByTestId('new-task').click();await page.getByTestId('task-title').fill('Защищённая работа');await page.getByTestId('save').click();await page.locator('#editor-dialog').waitFor({state:'hidden'});await page.getByTestId('task-toggle').click();await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).waitFor();
 if(mode!=='cancel')await page.evaluate(mode=>window.addEventListener('tasktimer:before-update',event=>event.detail.waitUntil(mode==='failed'?Promise.reject(Error('write failed')):new Promise(resolve=>{window.makeWaiting('replacement');resolve();}))),mode);
 page.once('dialog',dialog=>mode==='cancel'?dialog.dismiss():dialog.accept());await page.locator('[data-pwa-notice] [data-pwa-update]').click();if(mode!=='cancel')await page.locator('[data-pwa-update-error]').waitFor();
 assert.equal((await page.evaluate(()=>window.updateMessages)).includes('TASKTIMER_APPLY_UPDATE'),false);assert.equal(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),true);
 }finally{await context.close();}}
});
